version: '2'
services:
  vwadaptor:
    extends:
      file: docker-compose.yml
      service: vwadaptor
    env_file: ./.env.staging
    # number worker should be dependent on number of cpu cores.
    # usually 2-4 workers per cpu core
    command:  gunicorn -w 4 -b 0.0.0.0:5000 "app:app"
    volumes:
      - /data:/vwstorage
    depends_on:
      - postgres
      - redis
  swift:
    image: itsrifat/docker-swift-onlyone
    ports:
      - "8080:8080"
    depends_on:
      - swift_data
    volumes_from:
      - swift_data:rw
    environment:
      # This should be a secret key. its needed to enable temporary download url generation in swift
      SWIFT_TEMP_URL_KEY: something-very-secret
  swift_data:
    image: busybox
    volumes:
      - /srv
  redis:
    image: redis
  postgres:
    image: postgres
